empirical-soft/empirical-lang

- src/main.cpp
Make the REPL loop do slightly less work.
> Reduce work done in REPL

- tests/err.md
Patched ANTLR:
```
diff --git a/runtime/Cpp/runtime/src/NoViableAltException.cpp b/runtime/Cpp/runtime/src/NoViableAltException.cpp
index ced7f82..071b8c3 100755
--- a/runtime/Cpp/runtime/src/NoViableAltException.cpp
+++ b/runtime/Cpp/runtime/src/NoViableAltException.cpp
@@ -21,8 +21,11 @@ NoViableAltException::NoViableAltException(Parser *recognizer, TokenStream *inpu
}
NoViableAltException::~NoViableAltException() {
+  // Just let it leak for now; https://github.com/antlr/antlr4/issues/2550
+  /*
if (_deleteConfigs)
delete _deadEndConfigs;
+  */
}
Token* NoViableAltException::getStartToken() const {
```
fixes #18
> Fixed new crashing bug from parse errors

- scripts/website.sh
- src/VVM/utils/timestamp.cpp
- tests/CMakeLists.txt
- tests/time.md
- thirdparty/strtime/strtime.h
- thirdparty/strtime/timegm.c
> Parse timestamps prior to 1970-01-01

- doc/tutorial_core.md
- src/HIR.asdl
- src/codegen.cpp
- src/sema.cpp
> Added type_of() and columns()

- CONTRIBUTING.md
- MAINTAINING.md
- README.md
- scripts/build.sh
- src/VVM/bytecode.cpp
- src/VVM/interpret.cpp
- src/VVM/utils/timestamp.cpp
- src/VVM/utils/timestamp.hpp
- src/VVM/vvm.hpp
- src/codegen.cpp
- src/sema.cpp
- src/string_helpers.hpp
Ran clang-tidy for the first time. Went with [performance-unnecessary-value-param](https://clang.llvm.org/extra/clang-tidy/checks/performance-unnecessary-value-param.html) and [hicpp-use-emplace](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-emplace.html).
> Pass strings by reference if value is not needed

- doc/tutorial_running.md
- src/HIR.asdl
- src/sema.cpp
> HIR's declaration receives the decltype

- src/sema.cpp
- tests/traits.md
> Set function arguments to all traits

- src/HIR.asdl
- src/VVM/gen_vvm.py
- src/codegen.cpp
- src/sema.cpp
- tests/CMakeLists.txt
- tests/README.md
- tests/VVM/README.md
- tests/VVM/utils/README.md
- tests/assign.md
- tests/comptime.md
- tests/err.md
- tests/traits.md
Part of #44 
Still needs user-defined types and functions.
> Added literal-based CTFE on builtins; fixed handling of mutable variables

- src/HIR.asdl
- src/codegen.cpp
- src/sema.cpp
- tests/comptime.md
> Added compile() function

- src/VVM/utils/terminal.hpp
- src/codegen.cpp
- src/main.cpp
- src/sema.cpp
- tests/ctfe.emp
> Send comptime statements to VVM early to enable CTFE on user-defined items

- src/AST.asdl
- src/Empirical.g4
- src/HIR.asdl
- src/VVM/bytecode.cpp
- src/VVM/interpret.cpp
- src/VVM/vvm.hpp
- src/codegen.cpp
- src/empirical.hpp
- src/main.cpp
- src/parse.cpp
- src/sema.cpp
- tests/ctfe.emp
- tests/templates.emp
- thirdparty/asdl/asdl.py
- thirdparty/asdl/asdl_cpp.py
> Added function templates for literals; split VVM into runtime/comptime

- scripts/website.sh
- src/HIR.asdl
- src/codegen.cpp
- src/sema.cpp
- tests/comptime.md
- tests/err.md
- tests/templates.emp
> Added type parameters for templates; fixed bug when using templates in REPL

- src/AST.asdl
- src/Empirical.g4
- src/HIR.asdl
- src/codegen.cpp
- src/parse.cpp
- src/sema.cpp
- tests/comptime.md
- tests/ctfe.emp
- tests/templates.emp
> Added templates for data definitions; comptime VVM gets items on demand

- src/AST.asdl
- src/Empirical.g4
- src/HIR.asdl
- src/codegen.cpp
- src/main.cpp
- src/parse.cpp
- src/sema.cpp
- tests/inline.md
> Added inline functions

- src/AST.asdl
- src/Empirical.g4
- src/HIR.asdl
- src/VVM/vvm.hpp
- src/codegen.cpp
- src/parse.cpp
- src/sema.cpp
- tests/err.md
- tests/macro.emp
> Added macros

- README.md
- doc/tutorial.md
- src/AST.asdl
- src/Empirical.g4
- src/HIR.asdl
- src/VVM/gen_vvm.py
- src/codegen.cpp
- src/main.cpp
- src/parse.cpp
- src/sema.cpp
- tests/err.md
- tests/joins.md
- tests/load.emp
- tests/query.emp
- tests/sort.md
- tests/traits.md
> Migrated load$() to load()

- doc/tutorial.md
- src/VVM/gen_vvm.py
- tests/err.md
> Added int-to-float operators

- doc/tutorial.md
- src/VVM/gen_vvm.py
- src/VVM/interpret.cpp
- src/VVM/vvm.hpp
- src/empirical.hpp
- src/main.cpp
- src/sema.cpp
> Added exit() and argv

- doc/tutorial.md
- src/codegen.cpp
- tests/data.emp
> Fixed bug regarding constructors on data expressions

- src/codegen.cpp
- src/sema.cpp
- tests/generic.emp
> Added specialization of generic functions

- doc/tutorial.md
- src/AST.asdl
- src/Empirical.g4
- src/HIR.asdl
- src/codegen.cpp
- src/main.cpp
- src/parse.cpp
- src/sema.cpp
- tests/err.md
- tests/len.md
- tests/placeholders.emp
- tests/reverse.md
> Added generic placeholders

- src/sema.cpp
- tests/placeholders.emp
> Fixed bug when overloading placeholder generics

- src/VVM/gen_vvm.py
- src/VVM/interpret.cpp
- src/main.cpp
- tests/traits.md
> Added stream_load() as a stub to test streaming operations

- src/VVM/gen_vvm.py
- src/codegen.cpp
- tests/traits.md
> First pass at lineage

- src/sema.cpp
- tests/err_global.md
> Reset sema's scope if an error occurs

- src/VVM/gen_vvm.py
- src/VVM/interpret.cpp
- tests/math.md
> Added mean(), variance(), and stddev()

- src/VVM/gen_vvm.py
- src/VVM/interpret.cpp
- tests/len.md
- tests/reverse.md
> Added len() and reverse() for String

- .github/workflows/empirical.yml
> GitHub Actions can release binaries
